FROM registry.access.redhat.com/ubi7/ubi:7.9-601

COPY hue-copy /usr/share/hue

RUN set -eux; \
    yum install -y python27 curl \ 
    && curl -o get-pip.py https://bootstrap.pypa.io/pip/2.7/get-pip.py \
    && python get-pip.py \
    && useradd -ms /bin/bash hue && chown -R hue /usr/share/hue

EXPOSE 8888

CMD ["./entrypoint.sh"]